baseURL = "https://sjbdcs.org"
disableLanguages = []
disqusShortname = "sjbdcs"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "St John Baptist De La Salle Catholic School"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2022 St John Baptist De La Salle Catholic School, Addis Ababa"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher/"
[[Languages.en.menu.footer]]
name = "notice"
url = "notice/"
[[Languages.en.menu.footer]]
name = "event"
url = "event/"
[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship/"
[[Languages.en.menu.footer]]
name = "research"
url = "research/"
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1
[[Languages.en.menu.main]]
name = "course"
url = "course/"
weight = 2
[[Languages.en.menu.main]]
hasChildren = true
name = "Pages"
weight = 3
[[Languages.en.menu.main]]
name = "teacher"
parent = "Pages"
url = "teacher/"
[[Languages.en.menu.main]]
name = "notice"
parent = "Pages"
url = "notice/"
[[Languages.en.menu.main]]
name = "event"
parent = "Pages"
url = "event/"
[[Languages.en.menu.main]]
name = "scholarship"
parent = "Pages"
url = "scholarship/"
[[Languages.en.menu.main]]
name = "research"
parent = "Pages"
url = "research/"
[[Languages.en.menu.main]]
name = "blog"
url = "blog/"
weight = 4
[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 5
[params]
address = "Asco Addis Sefer"
author = "SJBDCS"
contact_form_action = "netlify"
description = "St John Baptist De La Salle Catholic School, Addis Ababa"
email = "communications@sjbdcs.org"
google_analitycs_id = ""
logo = "images/logo.png"
mobile = "+251112706132"
top_header = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "9.061537"
map_longitude = "38.6862893"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://sjbdcs.us17.list-manage.com/subscribe/post?u=7827c27f247d2d5406bae8797&amp;id=02e5a098e8"
mailchimp_form_name = "b_7827c27f247d2d5406bae8797_02e5a098e8"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/St-John-Baptist-De-La-Salle-Catholic-School-Addis-Ababa-100741619343302"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/sjbdcs"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/sjbdcs/"
title = "instagram"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/sjbdcs/"
title = "linkedin"
